name = "ContentHashes"
uuid = "ac509c8a-358f-4e3e-a88a-d19fed7814aa"
authors = ["Mike <michaelhatherly@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1.6"
